### ISSUE TITLE
什么鬼？还要注册也是无语

### ISSUE THREAD

**Issue by Danniel-yan** [DRPrincess/DR_WebviewDemo#1]
什么鬼？还要注册也是无语

**Comment by DRPrincess** [comment]
什么要注册？

**Comment by Danniel-yan** [comment]
可以了 需要下滑才能看到 非常感谢 解决了我遇到的问题发自我的iPhone------------------ 原始邮件 ------------------发件人: DRPrincess  <notifications@github.com>发送时间: 2019年3月5日 19:10收件人: DRPrincess/DR_WebviewDemo <DR_WebviewDemo@noreply.github.com>抄送: Daniel_yan <yshr1991@163.com>, Author <author@noreply.github.com>主题: 回复：[DRPrincess/DR_WebviewDemo] 什么鬼？还要注册也是无语 (#1)什么要注册？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DRPrincess/DR_WebviewDemo","title":"DRPrincess/DR_WebviewDemo","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DRPrincess/DR_WebviewDemo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DRPrincess in #1: 什么要注册？"}],"action":{"name":"View Issue","url":"https://github.com/DRPrincess/DR_WebviewDemo/issues/1#issuecomment-469640541"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DRPrincess/DR_WebviewDemo/issues/1#issuecomment-469640541",
"url": "https://github.com/DRPrincess/DR_WebviewDemo/issues/1#issuecomment-469640541",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
